services:
  server:
    build:
      context: ./server/TaskManager.Api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  client:
    build:
      context: ./client/task-manager
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
